---
- name: Install strongSwan
  yum:
    name=strongswan
    state=present


- name: Change sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_set: yes
  with_items:
  - { name: net.ipv4.ip_forward, value: 1 }
  - { name: net.ipv4.conf.eth0.disable_xfrm, value: 1 }
  - { name: net.ipv4.conf.eth0.disable_policy, value: 1 }

- name: Print version
  debug:
    msg: "{{ vpn_config }}"

- name: Deploy ipsec.conf
  template: src=ipsec.conf.j2 dest=/etc/strongswan/ipsec.conf
  notify: restart strongSwan

- name: Deploy ipsec.secrets
  template: src=ipsec.secrets.j2 dest=/etc/strongswan/ipsec.secrets
  notify: restart strongSwan

- name: Deploy ipsec-vti.sh
  template: src=ipsec-vti.sh.j2 dest=/etc/strongswan/ipsec-vti.sh
  notify: restart strongSwan

- name: Make ipsec-vti.sh exacutable
  file:
    path: /etc/strongswan/ipsec-vti.sh
    mode: "u=rwx,g=rwx,o-rwx"

- name: Enable and start strongSwan
  service:
    name: strongswan
    state: started
    enabled: yes