---

- name: Stop apprmor
  service:
    name: apparmor
    state: stopped
    enabled: no

- name: Update all packages
  apt:
    update_cache: yes


- name: Upgrade all packages
  apt:
    upgrade: full

- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip
  - nano
  - tcpdump

