---
- name: Install python module
  pip:
    name: "{{ item }}"
  with_items:
    - xmldict
    - boto3

- name: Copy VPN config generator
  copy:
    src=vpn_config_generator.py
    dest=/tmp/vpn_config_generator.py
