---
- name: Install BIRD
  apt:
    name=bird
    state=present

- name: Get default private ip
  uri:
    url: http://169.254.169.254/latest/meta-data/local-ipv4
    return_content: yes
  register: aws_private_ip

- name: Deploy bird.conf
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify: restart BIRD

- name: Create log file for BIRD
  file:
    path: /var/log/bird.log
    owner: bird
    group: bird
    mode: 0644
    state: touch

- name: Enable and start BIRD
  service:
    name: bird
    state: started
    enabled: yes